CREATE TABLE T_FIN_INVESTMENT(
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    description VARCHAR(255) NOT NULL,
    observation CLOB,
    amount NUMBER(10, 2) NOT NULL,
    "DATE" DATE NOT NULL,
    type VARCHAR(20),
    risk VARCHAR(10),
    liquidity VARCHAR(20),
    due_date DATE,
    profitability NUMBER(10, 2),
    origin_account_id NUMBER NOT NULL,
    interest_rate NUMBER(10, 2) NOT NULL,
    redeemed NUMBER(1) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP  NOT NULL,

    CONSTRAINT FK_INVESTMENT_ACCOUNT FOREIGN KEY (origin_account_id) REFERENCES T_FIN_ACCOUNT(ID)
)